### PR TITLE
Replace Unicode Symbols with ASCII Alternatives

### PR DESCRIPTION
**Pull request by Jaynator495**
Replaced ’ with '
Replaced − with -
Replaced × with x

### CODE REVIEW

**Comment by mizz141** [comment]
Might I ask why there is a need for this? Shouldn't ASCII be Deprecated in favor of UTF-8?

**Comment by Jaynator495** [comment]
The correct writing for the shows in English do not use Unicode, so it will be unlikely to be matched exactly. Some programs automatically insert those symbols, which is likely how they got there. (Wordpad, Word, such like that as it's commonly used in programs like that)

**Comment by mizz141** [comment]
Looking at my Logfiles it seems that the distinction doesn't matter https://imgur.com/a/NqSdAK1

@Raventhicc can you check too?

**Comment by Raventhicc** [comment]
Yea, I'll test it too

**Comment by mizz141** [comment]
Merged with #48 thanks.

**Pull request closed without merging**
