### PR TITLE
Added new seasons

### PR DESCRIPTION
**Pull request by BananaPukeh**

### CODE REVIEW

**Review by mizz141 — COMMENTED** [review]
Mushoku Tensei is completely wrong, needs to be fixed.

**Review by BananaPukeh — COMMENTED** [review]
@mizz141 Maybe not add S2 Part 2 yet, since the episodes are not matching. However if the amount of episodes on S1 Part 1 are correct it shouldn't matter if the anilist /tvdb numbers are not (yet) matching

**Comment by mizz141** [comment]
So, I've looked into this whole ordeal with mushoku, and it looks like the Anilist guys have a huge stick up their ass and just say that S00E02 is now S02E01, making it an offset by 1 for season 2.

Relevant:
https://submission-manual.anilist.co/Animated-Media-Criteria-0774daf8dd5f4e08a44a316b967a2161#b91475028b0d4aed8f98f32422bb43c3

https://anilist.co/forum/thread/66410

Oh, but don't fret, they surely didn't make S00E01 it's own entry https://anilist.co/anime/141534/Mushoku-Tensei-Jobless-Reincarnation-Cour-2--Eris-the-Goblin-Slayer/

I'll leave this open for now and see how this goes from there

**Comment by mizz141** [comment]
Alright, figured if we would drop S2 to a start of 0, it'll count 1 EP more, easy fix. 

I'll remake this PR due to the sorting stuff that was implemented

**Pull request closed without merging**
