### PR TITLE
Use guid for Ranma 1/2

### PR DESCRIPTION
**Pull request by evie-lau**
Ranma still couldn't match properly. Start using plex guid

### CODE REVIEW

**Comment by dear-clouds** [comment]
Shouldn't the guid be from the HAMA agent since PlexAniSync was made to work with that agent to begin with? Most users use HAMA. I personally had no issue matching the "Ranma ½ (2024)" title with HAMA. I think the synonyms should at least be kept for HAMA users using other languages :)

**Comment by evie-lau** [comment]
Hmm, I wasn't aware that the guid would be different with the HAMA agent. Do you know if multiple guids are supported?
Also I was under the impression that having a guid would override any synonym checks - may have to double check on that with PlexAniSync

**Comment by evie-lau** [comment]
Could you share the plex guid you have with the HAMA agent?
Instructions here: https://github.com/RickDB/PlexAniSync?tab=readme-ov-file#duplicate-plex-titles

And this does confirm that using guid will ignore title and synonyms

**Comment by dear-clouds** [comment]
The guid for HAMA looks like this: `com.plexapp.agents.hama://tvdb-452993?lang=en` but it depends on the user settings. Some use anidb instead or other languages so it's a bit complicated to use a unique guid with HAMA.

I've just checked the PlexAniSync doc, I had no idea it's supposed to ignore the title and synonyms when using guid. I've found that there's a [mapping between TVDB and TMDB](https://github.com/RickDB/PlexAniSync-Custom-Mappings/blob/main/series-tvdb.en.yaml) and Ranma is in there, which is why it worked for me. I guess, I'll make PR to RickDB directly if I have find titles without mapping in the future.

Sorry about that! 🙏

**Comment by evie-lau** [comment]
Ranma was only added very recently in that mapping file. I think yours was able to match before because the HAMA agent gave it a title that matched one of the title/synonyms you had contributed.

I use the Plex agent which named it `Ranma1/2`, which didn't exactly match any of the title/synonyms we had previously.
```
- title: "Ranma ½ (2024)"
    synonyms:
      - "Ranma 1/2 (2024)"
      - "らんま1/2 (2024)"
      - "Ranma 1/2 (New Anime)"
      - "Ranma 1/2 (Shinsaku Anime)"
      - "らんま1/2 (新作アニメ)"
```

**Comment by dear-clouds** [comment]
I watched an ep before you made changes and the last ep 2 days ago so that matches with the recent addition on the other mapping file. Because if it was using only this mapping, it wouldn't have worked with your changes since title is ignored now.

**Comment by mizz141** [comment]
In the meantime I'd suggest adding your own mapping in your local file, local entries override any remote-mappings.

**Comment by dear-clouds** [comment]
Yeah, it's all good, I'll keep using RickDB mapping since it works with HAMA and PR there directly in the future. Thanks!

**Pull request merged**
